name: Discord Notifications Bot

on:
  push:
  issues:
    types: [opened, closed, reopened]
  pull_request:
    types: [opened, closed, reopened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  release:
    types: [published]
  watch:
    types: [started]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      # 1. Pobieramy kod repozytorium (żeby mieć dostęp do pliku .js)
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Uruchamiamy skrypt Node.js
      - name: Run Discord Bot Script
        run: node .github/scripts/discord-bot.js
        env:
          # Przekazujemy sekret do skryptu
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          # Przekazujemy dane zdarzenia (to robi się automatycznie, ale warto wiedzieć)
          GITHUB_EVENT_PATH: ${{ github.event_path }}
